# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.arr_widget = QtWidgets.QTableWidget(self.centralwidget)
        self.arr_widget.setGeometry(QtCore.QRect(80, 160, 651, 281))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.arr_widget.setFont(font)
        self.arr_widget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.arr_widget.setObjectName("arr_widget")
        self.arr_widget.setColumnCount(0)
        self.arr_widget.setRowCount(0)
        self.arr_widget.horizontalHeader().setDefaultSectionSize(50)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(610, 580, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.vector_widget = QtWidgets.QTableWidget(self.centralwidget)
        self.vector_widget.setGeometry(QtCore.QRect(80, 500, 651, 51))
        self.vector_widget.setObjectName("vector_widget")
        self.vector_widget.setColumnCount(0)
        self.vector_widget.setRowCount(0)
        self.vector_widget.horizontalHeader().setDefaultSectionSize(50)
        self.fileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.fileBtn.setGeometry(QtCore.QRect(610, 50, 113, 31))
        self.fileBtn.setObjectName("fileBtn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 50, 91, 31))
        self.label_2.setObjectName("label_2")
        self.grp1 = QtWidgets.QGroupBox(self.centralwidget)
        self.grp1.setGeometry(QtCore.QRect(130, 70, 551, 81))
        self.grp1.setObjectName("grp1")
        self.rdBtnArrPV = QtWidgets.QRadioButton(self.grp1)
        self.rdBtnArrPV.setGeometry(QtCore.QRect(20, 50, 221, 20))
        self.rdBtnArrPV.setChecked(False)
        self.rdBtnArrPV.setObjectName("rdBtnArrPV")
        self.rdBtnArrRel = QtWidgets.QRadioButton(self.grp1)
        self.rdBtnArrRel.setGeometry(QtCore.QRect(270, 50, 221, 20))
        self.rdBtnArrRel.setObjectName("rdBtnArrRel")
        self.rdBtnArr = QtWidgets.QRadioButton(self.grp1)
        self.rdBtnArr.setGeometry(QtCore.QRect(20, 20, 191, 20))
        self.rdBtnArr.setCheckable(True)
        self.rdBtnArr.setChecked(False)
        self.rdBtnArr.setObjectName("rdBtnArr")
        self.rdBtnArrChance = QtWidgets.QRadioButton(self.grp1)
        self.rdBtnArrChance.setGeometry(QtCore.QRect(270, 20, 131, 20))
        self.rdBtnArrChance.setObjectName("rdBtnArrChance")
        self.grp2 = QtWidgets.QGroupBox(self.centralwidget)
        self.grp2.setGeometry(QtCore.QRect(110, 440, 551, 61))
        self.grp2.setObjectName("grp2")
        self.rdBtnPe = QtWidgets.QRadioButton(self.grp2)
        self.rdBtnPe.setGeometry(QtCore.QRect(30, 30, 191, 20))
        self.rdBtnPe.setChecked(False)
        self.rdBtnPe.setObjectName("rdBtnPe")
        self.rdBtnPeChance = QtWidgets.QRadioButton(self.grp2)
        self.rdBtnPeChance.setGeometry(QtCore.QRect(270, 30, 211, 20))
        self.rdBtnPeChance.setChecked(False)
        self.rdBtnPeChance.setObjectName("rdBtnPeChance")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Далі"))
        self.label.setText(_translate("MainWindow", "Вхідні данні"))
        self.fileBtn.setText(_translate("MainWindow", "Відкрити ..."))
        self.label_2.setText(_translate("MainWindow", "Вхідний файл:"))
        self.grp1.setTitle(_translate("MainWindow", "GroupBox"))
        self.rdBtnArrPV.setText(_translate("MainWindow", "Матриця перехресного впливу"))
        self.rdBtnArrRel.setText(_translate("MainWindow", "Матриця відношень шансів"))
        self.rdBtnArr.setText(_translate("MainWindow", "Матриця імовірності подій"))
        self.rdBtnArrChance.setText(_translate("MainWindow", "Матриця шансів"))
        self.grp2.setTitle(_translate("MainWindow", "GroupBox"))
        self.rdBtnPe.setText(_translate("MainWindow", "Вектор імовірностей"))
        self.rdBtnPeChance.setText(_translate("MainWindow", "Вектор безумовних впливів"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
