# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.arr_widget = QtWidgets.QTableWidget(self.centralwidget)
        self.arr_widget.setGeometry(QtCore.QRect(60, 40, 531, 281))
        self.arr_widget.setObjectName("arr_widget")
        self.arr_widget.setColumnCount(0)
        self.arr_widget.setRowCount(0)
        self.arr_name = QtWidgets.QLineEdit(self.centralwidget)
        self.arr_name.setGeometry(QtCore.QRect(60, 10, 181, 21))
        self.arr_name.setObjectName("arr_name")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(480, 340, 113, 32))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.arr_name.setText(_translate("MainWindow", "Матриця імовірності подій"))
        self.pushButton.setText(_translate("MainWindow", "Далі"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
